package com.jimulabs.mirrorsandbox.mockdata;

import java.util.Arrays;
import java.util.List;

/**
 * Created by lintonye on 15-03-04.
 */
public class ImageGen extends MockData.MockDataGenerator<ImageGen.MockImage> {
    @Override
    protected List<MockImage> getSamples() {
        return Arrays.asList(new MockImage("activity_market", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_market_1080.png"),
                new MockImage("activity_market", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_market_1980.png"),
                new MockImage("activity_market", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_market_360.png"),
                new MockImage("activity_mosque", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_mosque_1080.png"),
                new MockImage("activity_mosque", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_mosque_1980.png"),
                new MockImage("activity_mosque", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_mosque_360.png"),
                new MockImage("activity_restaurant", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_restaurant_1080.png"),
                new MockImage("activity_restaurant", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_restaurant_1980.png"),
                new MockImage("activity_restaurant", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/activity_restaurant_360.png"),
                new MockImage("animals_deer_snow_trees", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/animals_deer_snow_trees_1080.png"),
                new MockImage("animals_deer_snow_trees", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/animals_deer_snow_trees_1980.png"),
                new MockImage("animals_deer_snow_trees", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/animals_deer_snow_trees_360.png"),
                new MockImage("food_cake_coffee_cream", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_cake_coffee_cream_1080.png"),
                new MockImage("food_cake_coffee_cream", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_cake_coffee_cream_1980.png"),
                new MockImage("food_cake_coffee_cream", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_cake_coffee_cream_360.png"),
                new MockImage("food_catering_grapes_morsel", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_catering_grapes_morsel_1080.png"),
                new MockImage("food_catering_grapes_morsel", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_catering_grapes_morsel_1980.png"),
                new MockImage("food_catering_grapes_morsel", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_catering_grapes_morsel_360.png"),
                new MockImage("food_cookies_christmas", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_cookies_christmas_1080.png"),
                new MockImage("food_cookies_christmas", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_cookies_christmas_1980.png"),
                new MockImage("food_cookies_christmas", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_cookies_christmas_360.png"),
                new MockImage("food_drink_lemon_orange", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_drink_lemon_orange_1080.png"),
                new MockImage("food_drink_lemon_orange", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_drink_lemon_orange_1980.png"),
                new MockImage("food_drink_lemon_orange", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_drink_lemon_orange_360.png"),
                new MockImage("food_herbs_scissors_sage", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_herbs_scissors_sage_1080.png"),
                new MockImage("food_herbs_scissors_sage", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_herbs_scissors_sage_1980.png"),
                new MockImage("food_herbs_scissors_sage", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_herbs_scissors_sage_360.png"),
                new MockImage("food_meat_garlic_pepper", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_meat_garlic_pepper_1080.png"),
                new MockImage("food_meat_garlic_pepper", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_meat_garlic_pepper_1980.png"),
                new MockImage("food_meat_garlic_pepper", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_meat_garlic_pepper_360.png"),
                new MockImage("food_tomato_knife_vegtables", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_tomato_knife_vegtables_1080.png"),
                new MockImage("food_tomato_knife_vegtables", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_tomato_knife_vegtables_1980.png"),
                new MockImage("food_tomato_knife_vegtables", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/food_tomato_knife_vegtables_360.png"),
                new MockImage("gifts_flower_rose", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_flower_rose_1080.png"),
                new MockImage("gifts_flower_rose", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_flower_rose_1980.png"),
                new MockImage("gifts_flower_rose", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_flower_rose_360.png"),
                new MockImage("gifts_party_wine_light", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_party_wine_light_1080.png"),
                new MockImage("gifts_party_wine_light", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_party_wine_light_1980.png"),
                new MockImage("gifts_party_wine_light", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_party_wine_light_360.png"),
                new MockImage("gifts_tree_christmas", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_tree_christmas_1080.png"),
                new MockImage("gifts_tree_christmas", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_tree_christmas_1980.png"),
                new MockImage("gifts_tree_christmas", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/gifts_tree_christmas_360.png"),
                new MockImage("landscape_autunm_tree_bench", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_autunm_tree_bench_1080.png"),
                new MockImage("landscape_autunm_tree_bench", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_autunm_tree_bench_1980.png"),
                new MockImage("landscape_autunm_tree_bench", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_autunm_tree_bench_360.png"),
                new MockImage("landscape_beach_sea", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_beach_sea_1080.png"),
                new MockImage("landscape_beach_sea", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_beach_sea_1980.png"),
                new MockImage("landscape_beach_sea", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_beach_sea_360.png"),
                new MockImage("landscape_bridge", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_bridge_1080.png"),
                new MockImage("landscape_bridge", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_bridge_1980.png"),
                new MockImage("landscape_bridge", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_bridge_360.png"),
                new MockImage("landscape_evergreen_tree_chrismas", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_evergreen_tree_chrismas_1080.png"),
                new MockImage("landscape_evergreen_tree_chrismas", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_evergreen_tree_chrismas_1980.png"),
                new MockImage("landscape_evergreen_tree_chrismas", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_evergreen_tree_chrismas_360.png"),
                new MockImage("landscape_forest_river", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_forest_river_1080.png"),
                new MockImage("landscape_forest_river", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_forest_river_1980.png"),
                new MockImage("landscape_forest_river", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_forest_river_360.png"),
                new MockImage("landscape_house_tree_chrismas", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_house_tree_chrismas_1080.png"),
                new MockImage("landscape_house_tree_chrismas", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_house_tree_chrismas_1980.png"),
                new MockImage("landscape_house_tree_chrismas", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_house_tree_chrismas_360.png"),
                new MockImage("landscape_mountain_forest", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_mountain_forest_1080.png"),
                new MockImage("landscape_mountain_forest", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_mountain_forest_1980.png"),
                new MockImage("landscape_mountain_forest", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_mountain_forest_360.png"),
                new MockImage("landscape_mountains_river_night", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_mountains_river_night_1080.png"),
                new MockImage("landscape_mountains_river_night", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_mountains_river_night_1980.png"),
                new MockImage("landscape_mountains_river_night", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_mountains_river_night_360.png"),
                new MockImage("landscape_palm", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_palm_1080.png"),
                new MockImage("landscape_palm", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_palm_1980.png"),
                new MockImage("landscape_palm", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_palm_360.png"),
                new MockImage("landscape_tree_hill", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_tree_hill_1080.png"),
                new MockImage("landscape_tree_hill", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_tree_hill_1980.png"),
                new MockImage("landscape_tree_hill", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_tree_hill_360.png"),
                new MockImage("landscape_tree_park", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_tree_park_1080.png"),
                new MockImage("landscape_tree_park", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_tree_park_1980.png"),
                new MockImage("landscape_tree_park", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_tree_park_360.png"),
                new MockImage("landscape_winter_snow_tree", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_winter_snow_tree_1080.png"),
                new MockImage("landscape_winter_snow_tree", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_winter_snow_tree_1980.png"),
                new MockImage("landscape_winter_snow_tree", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/landscape_winter_snow_tree_360.png"),
                new MockImage("monster_cyclop_eye", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_cyclop_eye_1080.png"),
                new MockImage("monster_cyclop_eye", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_cyclop_eye_1980.png"),
                new MockImage("monster_cyclop_eye", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_cyclop_eye_360.png"),
                new MockImage("monster_nessi_scottland_water", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_nessi_scottland_water_1080.png"),
                new MockImage("monster_nessi_scottland_water", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_nessi_scottland_water_1980.png"),
                new MockImage("monster_nessi_scottland_water", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_nessi_scottland_water_360.png"),
                new MockImage("monster_suitcase_spider", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_suitcase_spider_1080.png"),
                new MockImage("monster_suitcase_spider", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_suitcase_spider_1980.png"),
                new MockImage("monster_suitcase_spider", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/monster_suitcase_spider_360.png"),
                new MockImage("office_book_hand_holding", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_book_hand_holding_1080.png"),
                new MockImage("office_book_hand_holding", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_book_hand_holding_1980.png"),
                new MockImage("office_book_hand_holding", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_book_hand_holding_360.png"),
                new MockImage("office_chart_plant", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_chart_plant_1080.png"),
                new MockImage("office_chart_plant", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_chart_plant_1980.png"),
                new MockImage("office_chart_plant", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_chart_plant_360.png"),
                new MockImage("office_glue_tape_paperclip", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_glue_tape_paperclip_1080.png"),
                new MockImage("office_glue_tape_paperclip", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_glue_tape_paperclip_1980.png"),
                new MockImage("office_glue_tape_paperclip", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/office_glue_tape_paperclip_360.png"),
                new MockImage("shopping_shoes_carpet", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/shopping_shoes_carpet_1080.png"),
                new MockImage("shopping_shoes_carpet", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/shopping_shoes_carpet_1980.png"),
                new MockImage("shopping_shoes_carpet", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/shopping_shoes_carpet_360.png"),
                new MockImage("space_asteroid", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_asteroid_1080.png"),
                new MockImage("space_asteroid", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_asteroid_1980.png"),
                new MockImage("space_asteroid", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_asteroid_360.png"),
                new MockImage("space_monster", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_monster_1080.png"),
                new MockImage("space_monster", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_monster_1980.png"),
                new MockImage("space_monster", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_monster_360.png"),
                new MockImage("space_planet", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_planet_1080.png"),
                new MockImage("space_planet", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_planet_1980.png"),
                new MockImage("space_planet", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_planet_360.png"),
                new MockImage("space_rocket", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_rocket_1080.png"),
                new MockImage("space_rocket", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_rocket_1980.png"),
                new MockImage("space_rocket", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_rocket_360.png"),
                new MockImage("space_ship", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_ship_1080.png"),
                new MockImage("space_ship", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_ship_1980.png"),
                new MockImage("space_ship", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_ship_360.png"),
                new MockImage("space_startrek_intro_voyager_planet", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_startrek_intro_voyager_planet_1080.png"),
                new MockImage("space_startrek_intro_voyager_planet", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_startrek_intro_voyager_planet_1980.png"),
                new MockImage("space_startrek_intro_voyager_planet", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/space_startrek_intro_voyager_planet_360.png"),
                new MockImage("sport_bike_racing", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_bike_racing_1080.png"),
                new MockImage("sport_bike_racing", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_bike_racing_1980.png"),
                new MockImage("sport_bike_racing", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_bike_racing_360.png"),
                new MockImage("sport_rowing_river_boat", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_rowing_river_boat_1080.png"),
                new MockImage("sport_rowing_river_boat", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_rowing_river_boat_1980.png"),
                new MockImage("sport_rowing_river_boat", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_rowing_river_boat_360.png"),
                new MockImage("sport_running_park", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_running_park_1080.png"),
                new MockImage("sport_running_park", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_running_park_1980.png"),
                new MockImage("sport_running_park", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_running_park_360.png"),
                new MockImage("sport_skiing_winter_mountain", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_skiing_winter_mountain_1080.png"),
                new MockImage("sport_skiing_winter_mountain", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_skiing_winter_mountain_1980.png"),
                new MockImage("sport_skiing_winter_mountain", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_skiing_winter_mountain_360.png"),
                new MockImage("sport_swimming_race", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_swimming_race_1080.png"),
                new MockImage("sport_swimming_race", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_swimming_race_1980.png"),
                new MockImage("sport_swimming_race", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_swimming_race_360.png"),
                new MockImage("sport_yoga_morning", 1080, 1080, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_yoga_morning_1080.png"),
                new MockImage("sport_yoga_morning", 1980, 1980, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_yoga_morning_1980.png"),
                new MockImage("sport_yoga_morning", 360, 360, "https://raw.githubusercontent.com/jimulabs/lorem-ipsum-illustration/master/png/sport_yoga_morning_360.png"));
    }
    
    static class MockImage {
        final String name, url;
        final int width, height;

        MockImage(String name, int width, int height, String url) {
            this.name = name;
            this.width = width;
            this.height = height;
            this.url = url;
        }
    }
}
