package com.jimulabs.mirrorsandbox.mockdata;

import java.util.Arrays;
import java.util.List;

/**
 * Created by lintonye on 15-03-04.
 */
public class PersonNameGen extends MockData.MockDataGenerator<String> {
    @Override
    protected List<String> getSamples() {
        return Arrays.asList("Marilyn Monroe",
                "Abraham Lincoln",
                "Mother Teresa",
                "John F. Kennedy",
                "Martin Luther King",
                "Nelson Mandela",
                "Winston Churchill",
                "Bill Gates",
                "Muhammad Ali",
                "Mahatma Gandhi",
                "Margaret Thatcher",
                "Charles de Gaulle",
                "Christopher Columbus",
                "George Orwell",
                "Charles Darwin",
                "Elvis Presley",
                "Albert Einstein",
                "Paul McCartney",
                "Plato",
                "Queen Elizabeth II",
                "Queen Victoria",
                "John M Keynes",
                "Mikhail Gorbachev",
                "Jawaharlal Nehru",
                "Leonardo da Vinci",
                "Louis Pasteur",
                "Leo Tolstoy",
                "Pablo Picasso",
                "Vincent Van Gogh",
                "Franklin D. Roosevelt",
                "Pope John Paul II",
                "Thomas Edison",
                "Rosa Parks",
                "Aung San Suu Kyi",
                "Lyndon Johnson",
                "Ludwig Beethoven",
                "Oprah Winfrey",
                "Indira Gandhi",
                "Eva Peron",
                "Benazir Bhutto",
                "Desmond Tutu",
                "Dalai Lama",
                "Walt Disney",
                "Neil Armstrong",
                "Peter Sellers",
                "Barack Obama",
                "Malcolm X",
                "J.K.Rowling",
                "Richard Branson",
                "Pele",
                "Angelina Jolie",
                "Jesse Owens",
                "Ernest Hemingway",
                "John Lennon",
                "Henry Ford",
                "Haile Selassie",
                "Joseph Stalin",
                "Lord Baden Powell",
                "Michael Jordon",
                "George Bush jnr",
                "V.Lenin",
                "Ingrid Bergman",
                "Fidel Castro",
                "Oscar Wilde",
                "Coco Chanel",
                "Pope Francis",
                "Amelia Earhart",
                "Adolf Hitler",
                "Sting",
                "Mary Magdalene",
                "Alfred Hitchcock",
                "Michael Jackson",
                "Madonna",
                "Mata Hari",
                "Cleopatra",
                "Grace Kelly",
                "Steve Jobs",
                "Ronald Reagan",
                "Lionel Messi",
                "Babe Ruth",
                "Bob Geldof",
                "Leon Trotsky",
                "Roger Federer",
                "Sigmund Freud",
                "Woodrow Wilson",
                "Mao Zedong",
                "Katherine Hepburn",
                "Audrey Hepburn",
                "David Beckham",
                "Tiger Woods",
                "Usain Bolt",
                "Carl Lewis",
                "Prince Charles",
                "Jacqueline Kennedy Onassis",
                "C.S. Lewis",
                "Billie Holiday",
                "J.R.R. Tolkien",
                "Tom Cruise",
                "Billie Jean King",
                "Anne Frank");
    }
}
